import { cn } from "@/app/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ContextProvider from "./Context/store";
import "./globals.css";
import Navbar from "./ui/Navbar";
import Sidebar from "./ui/Sidebar";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          inter.className
        )}
      >
        <ContextProvider>
          <section className="h-screen w-screen">
            <main className="h-full flex">
              <Sidebar />
              <div className="flex-grow max-w-full overflow-hidden">
                <Navbar />
                <div className="h-[calc(100vh-49px)] py-5 flex items-start justify-evenly overflow-y-auto">
                  {children}
                </div>
              </div>
            </main>
          </section>
        </ContextProvider>
      </body>
    </html>
  );
}
