import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ContextProvider from "./Context/store";
import "./globals.css";
import Navbar from "@/app/ui/Navbar";
import Sidebar from "@/app/ui/Sidebar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased overflow-x-hidden",
          inter.className
        )}
      >
        <ContextProvider>
          <section className="min-h-screen">
            <main className="min-h-screen flex">
              <Sidebar />
              <div className="flex-grow max-w-full overflow-x-hidden xl:overflow-y-hidden">
                <Navbar />
                <div className="py-5 xl:px-4 flex flex-col items-center justify-evenly overflow-y-auto xl:flex-row xl:items-start xl:h-[calc(100vh-49px)]">
                  {children}
                </div>
              </div>
            </main>
          </section>
        </ContextProvider>
        <Toaster />
      </body>
    </html>
  );
}
